spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: ERP.pojo
  mapper-locations: classpath:mappers/*.xml